name: build
on: push
#env:
# build_needed: no
#  versions: "test"
jobs:
  check:
    runs-on: ubuntu-latest
    container: 'debian:11'
    #outputs:
    #  matrix: ${{ steps.set-matrix.outputs.matrix }}
    #  needed: no
    steps:
      - name: install curl
        run: apt-get update; apt-get -y install curl
      - name: check for the build needed flag
        run: echo "::set-output name=needed::yes"
      #- name: trigger builds  if needed
      #  id: set-matrix
      #  if: env.build_needed == 'no'
      #  run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"Stretch\"},{\"project\":\"Buster\"},{\"project\":\"Bullseye\"}]}"
  build:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["Stretch","Buster","Bullseye"]
    if: ${{ needs.check.outputs.needed == 'yes' }}
    steps:
      - run: echo "test"
