name: build installer images
on:
  push:
    paths:
      - '.rebuild'
  schedule:
     - cron: "*/15 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    container: 'debian:11'
    outputs:
      needed: ${{ steps.flag-check.outputs.needed }}
    steps:
      - name: install curl
        run: apt-get update; apt-get -y install curl
      - name: check for the build needed flag
        id: flag-check
        run: echo "::set-output name=needed::$(curl -sL https://github.com/1000001101000/Debian_on_Buffalo/raw/master/.rebuild 2>/dev/null)"
  
  build:
    needs: check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "/Debian_on_Buffalo"
    container: 'debian:11'
    if: ${{ needs.check.outputs.needed == 'yes' }}
    steps:
      - name: install prereqs
        run: apt-get update; apt-get -y install gzip rsync wget cpio faketime u-boot-tools libarchive-cpio-perl devio curl git gawk xz-utils
        working-directory: "/"
      - name: clone repo 
        run: git clone --depth 1 https://github.com/${{github.repository}}
        working-directory: "/"
      - name: run build script
        run: ./.github/build_all.sh
      - name: clear rebuild flag
        run: echo no > .rebuild
      - name: setup git config
        run: git config user.name "workflow@github"; git config user.email "workflow@github"
      - name: commit new files to branch
        run: git stage ./*; git commit -v -a -m "update installer images"
      - name: push
        run: git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git master
          
   
      
