name: build
on: push
env:
  build_needed: no
  versions: "test"
jobs:
  check:
    runs-on: ubuntu-latest
    container: 'debian:11'
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: install curl
        run: apt-get update; apt-get -y install curl
      - name: check for the build needed flag
        run: echo "build_needed=$(curl -sL https://github.com/1000001101000/Debian_on_Buffalo/raw/master/.rebuild 2>/dev/null)"  >> $GITHUB_ENV
        
      #- name: trigger builds  if needed
      #  id: set-matrix
      #  if: env.build_needed == 'no'
      #  run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"Stretch\"},{\"project\":\"Buster\"},{\"project\":\"Bullseye\"}]}"
  build:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["Stretch","Buster","Bullseye"]
    if: ${{ build_needed == 'no' }}
    steps:
      - run: echo "test"
