name: Update installer images

on: push
 # push:
 #   paths: 
 #     - '.rebuild'
 # schedule: 
 #    - cron: "*/15 * * * *"

jobs:
  setup:
    runs-on: ubuntu-latest
    container: 'debian:11'
    outputs:
      distros: ${{ steps.set-matrix.outputs.matrix }}
    env:
      repo_dir: .
      build_needed: no
      versions: '{["Stretch", "Buster", "Bullseye"]}'
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      
    steps: 
    - name: update apt
      run: apt-get update
    
    - name: install curl
      run: apt-get -y install curl
    
    ##check for build flag, 
    - name: check for the build needed flag
      run: echo "build_needed=$(curl -sL https://github.com/1000001101000/Debian_on_Buffalo/raw/master/.rebuild 2>/dev/null)"  >> $GITHUB_ENV
      
    - name: trigger builds if needed
      id: set-matrix
      if: env.build_needed == 'yes'
      run: echo "::set-output name=matrix::env.versions"
      
  build:
    needs: setup
    runs-on: ubuntu-latest
    container: 'debian:11'      
    strategy:
      matrix:
        version: ${{ fromJson(needs.setups.outputs.distros) }}
    steps:
      - name: ensure build packages are installed
        run: echo "test"
    
    
 
