name: Check for kernel updates

on: [push] 
  #schedule:
  #  - cron: 10 * * * *

jobs:
  build_stretch:
    runs-on: ubuntu-latest
    container: 'debian:9'
    env:
      repo_dir: .
      build_needed: no
    
    steps: 
    - name: update apt
      run: apt-get update
    
    - name: install needed packages
      run: apt-get -y install curl gawk
      
    ##curl to get the last version we built
    
    ##apt-cache to get the latest source version
    - name: get current linux-source version
      run: apt-cache show linux-source-4.9 | grep -m 1 Version | gawk '{print $2}' | tee /tmp/stretch_kernel.txt
  
    - name: download kernel source and build tools. 
      run: apt-get -y install linux-source-4.9 libc6-armel-cross libc6-dev-armel-cross binutils-arm-linux-gnueabi libncurses5-dev gcc-arm-linux-gnueabi build-essential git
  
    - name: unpack kernel
      run: tar xf linux-source-4.9.tar.xz
      working-directory: /usr/src/
    
    - name: copy in config
      run: curl -sL https://github.com/${{github.repository}}/raw/master/Tools/kernel_tools/configs/custom-config-4.9 > .config
      working-directory: /usr/src/linux-source-4.9/
    
    - name: make config
      run: make ARCH=arm oldconfig
      working-directory: /usr/src/linux-source-4.9/
      
    - name: try make
      run: make -j4 ARCH=arm KBUILD_DEBARCH=armel CROSS_COMPILE="arm-linux-gnueabi-" bindeb-pkg
      working-directory: /usr/src/linux-source-4.9/
      
  ## if not matched, download cross tools some where
    ## clone repo
    ##auto bump verison? .. need to grab it first
    ##... configure build script for cross location?
    ## run the build, might take a while
    
    ##copy/commit resulting deb somewhere for testing?
    
    ##should be able to do for 4.12, 4.19, 5.x in parellel via buster images.
